export const GET_DATA = 'getData'
export const GET_STU_DATA = 'getStudentData'
export const ADD_STU_DATA = 'addStudentData'
export const GET_STU_A_DATA = 'getStudentALevelData'
export const GET_STU_ANOMIE_DATA = 'getStudentAnomieData'
export const GET_STU_LEARN_D_DATA = 'getStudentLearnDiffData'
export const GET_STU_MINORITY_DATA = 'getStudentMinorityData'
export const GET_STU_HAS_RELIGION_DATA = 'getStuHasReligionData'